<?php
require 'includes/db_config.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit();
}

// Get all reports
$query = "SELECT r.*, u.full_name as generated_by_name
          FROM reports r
          LEFT JOIN users u ON r.generated_by = u.id
          ORDER BY r.created_at DESC";
$result = mysqli_query($conn, $query);
$reports = array();
while($row = mysqli_fetch_assoc($result)) {
    $reports[] = $row;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports - Faculty Management System</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        .reports-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .reports-table th, .reports-table td { padding: 12px; text-align: left; border-bottom: 1px solid var(--border-color); }
        .reports-table th { background: var(--primary-color); color: white; font-weight: 600; }
        .report-type { padding: 5px 12px; border-radius: 6px; background: rgba(109, 40, 217, 0.1); color: var(--primary-color); font-size: 0.85rem; font-weight: 600; }
    </style>
</head>
<body>
    <?php include 'includes/sidebar.php'; ?>
    
    <div class="main-content">
        <?php include 'includes/header.php'; ?>
        
        <div class="dashboard-container">
            <h1 class="page-title">REPORTS</h1>
            
            <div style="background: white; padding: 20px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08);">
                <table class="reports-table">
                    <thead>
                        <tr>
                            <th>Report Type</th>
                            <th>Title</th>
                            <th>Period</th>
                            <th>Generated By</th>
                            <th>Date Generated</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(count($reports) > 0): ?>
                            <?php foreach($reports as $report): ?>
                                <tr>
                                    <td><span class="report-type"><?php echo $report['report_type']; ?></span></td>
                                    <td><?php echo $report['title']; ?></td>
                                    <td><?php echo date('d-M-Y', strtotime($report['period_start'])) . ' to ' . date('d-M-Y', strtotime($report['period_end'])); ?></td>
                                    <td><?php echo $report['generated_by_name'] ?? 'System'; ?></td>
                                    <td><?php echo date('d-M-Y H:i', strtotime($report['created_at'])); ?></td>
                                    <td><a href="#" class="btn btn-sm" style="padding: 5px 12px;"><i class="fas fa-download"></i></a></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr><td colspan="6" style="text-align: center; color: #999;">No reports available</td></tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
        
        <?php include 'includes/footer.php'; ?>
    </div>
</body>
</html>
